- .github/workflows/deploy.yaml
- .github/workflows/deploy.yml
- .gitmodules
This continuous integration workflow cross-compiles Nickel to WASM,
then builds the rest of the website, and deploys the whole thing to
Netlify using the Netlify CLI. Netlify automatic builds should
therefore be disabled. We use GitHub Actions for the build instead of
Netlify because that way we can use Nix.
The Nickel repo is tracked as a submodule. Changes to the Nickel repo
are *not* automatically reflected on the website. Instead, the website
tracks releases (once these exist). Deploying changes to Nickel on the
website requires updating the submodule reference by hand.
> Add CI GitHub Actions workflow

- src/ace-nickel-mode/ace-nickel-mode.js
When typing `ctrl+/` to comment out code in the playground, it currently inserts `//` which, rather than commenting out the line, just results in syntax errors. This fixes that.
> Change playground line comment char to `#`

- src/ace-nickel-mode/ace-nickel-mode.js
Nickel has changed since the playground syntax highlighting was set up. This PR updates the syntax highlighting to (mostly) match the language as it is today.
> Fix syntax highlighting in playground

- package-lock.json
- package.json
Will open an issue to remember to remove the override once ansi-to-react has been updated upstream. See https://github.com/nteract/ansi-to-react/issues/80.
> Override ansi-to-react to work with react 18 and fix deployment

- src/pages/getting-started.js
in order to keep the documentation in sync with stable nickel branch, it's important to use github:tweag/nickel/stable to not have the development version of nickel with which the documentation may not be in sync
> switch nix commands examples to stable branch

- src/pages/getting-started.js
we should find a more future proof solution, but better update it right now until that time
> bump docker link to nickel 0.3.1

- src/components/sidebar-toc.js
This fixes #335 by just avoiding relative links in the sidebar that might pick up a trailing `/` and cause the confusion described there. It feels like a bit of a hack, but it seems to work.
> Use absolute links in the sidebar ToC

- .gitignore
- gatsby-config.js
- gatsby-node.js
- package-lock.json
- plugins/gatsby-remark-mangle-links/index.js
- plugins/gatsby-remark-mangle-links/package.json
Add a small and very specific plugin for `gatsby-transformer-remark` that mangles certain relative links in the user manual. This fixes spurious 404 errors which appeared before redirecting the user to the proper place.
> Mangle internal markdown links in the user manual

- src/ace-nickel-mode/ace-nickel-mode.js
- src/prism/nickel.js
Update the ACE and Prism highlighting rules for 1.0 Nickel syntax changes.
> Update highlighting grammars

- flake.lock
With this, the `unstable` branch preview will include the latest changes in the Nickel user manual.
> Run nix flake update

- flake.lock
A small fix has been made upstream on `nickel/stable` (roadmap was outdated). This commit updates the corresponding flake input to include those changes on the deployed version of the website.
> Update Nickel input to include roadmap fix

- src/components/footer.js
This adds an invite link to the Nickel Matrix space to the website footer. Fontawesome doesn't seem to have a Matrix icon, so I'm using `message` instead for now.
> Link matrix space in the footer

- src/pages/getting-started.js
The Getting Started guide was still linking to the 0.3.1 docker image.
> Update docker image version in getting-started

- src/pages/getting-started.js
nickel 1.0 is availble in homebrew so why not tell the macOS people about it.
> add instructions for install via homebrew

- LICENSE
Tweag has been acquired in 2022 by Modus Create. This PR updates the various licenses to reflect this change legally.
> [Meta] Update the copyright holder to Modus

- src/pages/stdlib/{StdlibSection.slug}.js
The `types` to `type` rename in Nickel upstream will break the stdlib documentation generation on the next release, otherwise. Accordingly, we shouldn't merge this into `master` until then.
> Change `types` to `type` when generating stdlib documentation

- gatsby-config.js
- src/pages/user-manual/{UserManualMarkdown.slug}.js
- src/prism/nickel.js
This makes Prismjs understand the new code block annotations needed for https://github.com/tweag/nickel/pull/1611
This should be compatible with current manual as well.
> Add support for more `nickel` code block annotations

- src/pages/getting-started.js
Added a space after the link to the advanced tutorial.
Before:
> In particular, the [last section](https://nickel-lang.org/user-manual/tutorial)is a slighty more advanced tutorial.
After:
> In particular, the [last section](https://nickel-lang.org/user-manual/tutorial) is a slighty more advanced tutorial.
> Fix typo in Getting Started page

- src/components/footer.js
Tweag decided to make all communication channels related to FOSS projects public, instead of hosting them internally on Slack, which wasn't contributor-friendly. We also settled on a common instant messaging platform, and for a number of reasons, Discord was picked.
Thus the Nickel instant messaging channel has been moved from Matrix to Discord. The Matrix channel is still there and is bridged with the Discord one, but we want to redirect new users directly to the Discord one.
This PR removes a mention to Matrix and updates it with the Discord's channel link.
> Update link to IM from Matrix to Discord

- src/pages/getting-started.js
Plus update the version of the docker image to use.
> Update getting started page for 1.3 CLI syntax

- flake.lock
In particular, stable (1.5.0) has been updated with a small fix in the manual's introduction which doesn't mention the current version anymore.
> Update to latest stable

- gatsby-config.js
The new section of the manual is accessible with a direct URL, but isn't part of the table of content on the left when browsing the user manual.
> Make the new modular configs manual section visible

- src/pages/getting-started.js
Mention and link to the pre-built binaries as the preferred method for installation. Prefer Nixpkgs over using the Nickel flake directly. Update the docker image example to the current released version.
Some part of the diff is just noise, my auto-formatter kicked in. Sorry.
> Refresh getting started page

- src/components/footer.js
- src/components/playground-clientside.js
- src/components/playground/playground.js
- src/pages/index.js
Fixes #757.
Following #750, we've updated from Bootstrap 4 to Bootstrap 5. It seems that `text-left` and `text-right` have been replaced with `text-start` and `text-end`, hence the misalignment. I've also discovered some other breaking changes fixed in this PR (https://getbootstrap.com/docs/5.0/migration/).
> Fix alignement class for Bootstrap 4 -> Bootstrap 5

- gatsby-config.js
- package-lock.json
- package.json
Every now and then (probably when my browser cache is empty), clicking on the "stdlib" link on nickel-lang.org flashes a 404 page for a second or so before redirecting me to the stdlib. This PR does two things to (hopefully) fix this:
- it changes the "stdlib" links to point to the actual location of the stdlib docs, avoiding the need for the redirect
- in case other parts of the site rely on the redirect from /stdlib to /stdlib/std, it adds the gatsby-plugin-netlify plugin to automatically generate a netlify `_redirect` file for all our redirects; I learned about the need for this [here](https://github.com/gatsbyjs/gatsby/issues/26218). This extra plugin might be overkill -- we could write our own `_redirect` file -- but it makes it easy to keep things in sync.
> Improve the stdlib redirect
